//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code2012Survey {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizeText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizeText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Code2012Survey.LocalizeText", typeof(LocalizeText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept..
        /// </summary>
        public static string AcceptNotice {
            get {
                return ResourceManager.GetString("AcceptNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do you write code?.
        /// </summary>
        public static string CaptionQ1 {
            get {
                return ResourceManager.GetString("CaptionQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long years do you write code?.
        /// </summary>
        public static string CaptionQ2 {
            get {
                return ResourceManager.GetString("CaptionQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you live in, or come from? (Country name).
        /// </summary>
        public static string CaptionQ3 {
            get {
                return ResourceManager.GetString("CaptionQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us to your passion for writing code..
        /// </summary>
        public static string CaptionQ4 {
            get {
                return ResourceManager.GetString("CaptionQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy the ability to create something..
        /// </summary>
        public static string Choice1OfQ1 {
            get {
                return ResourceManager.GetString("Choice1OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant feedback..
        /// </summary>
        public static string Choice2OfQ1 {
            get {
                return ResourceManager.GetString("Choice2OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just love to solve puzzles or various problems..
        /// </summary>
        public static string Choice3OfQ1 {
            get {
                return ResourceManager.GetString("Choice3OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because they do not like people..
        /// </summary>
        public static string Choice4OfQ1 {
            get {
                return ResourceManager.GetString("Choice4OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill a need..
        /// </summary>
        public static string Choice5OfQ1 {
            get {
                return ResourceManager.GetString("Choice5OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make money..
        /// </summary>
        public static string Choice6OfQ1 {
            get {
                return ResourceManager.GetString("Choice6OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your replay posted complete..
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is taht OK?.
        /// </summary>
        public static string ConfirmPrompt {
            get {
                return ResourceManager.GetString("ConfirmPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string GoNext {
            get {
                return ResourceManager.GetString("GoNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Code2012&quot; Event Site.
        /// </summary>
        public static string JumpToCode201OfficialSite {
            get {
                return ResourceManager.GetString("JumpToCode201OfficialSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone can get or view the post data which you send from this survey via public API on the Internet..
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code2012 Survey.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your replay!.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string UnitOfYears {
            get {
                return ResourceManager.GetString("UnitOfYears", resourceCulture);
            }
        }
    }
}
