//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code2012Survey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Code2012Survey.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上記について理解しました。.
        /// </summary>
        public static string AcceptNotice {
            get {
                return ResourceManager.GetString("AcceptNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 何故あなたは、コードを書くのでしょうか?.
        /// </summary>
        public static string CaptionQ1 {
            get {
                return ResourceManager.GetString("CaptionQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたの &quot;コード歴&quot; を教えてください。.
        /// </summary>
        public static string CaptionQ2 {
            get {
                return ResourceManager.GetString("CaptionQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差し支えなければ、あなたの活動拠点の都道府県名、あるいは、国名を教えてください。.
        /// </summary>
        public static string CaptionQ3 {
            get {
                return ResourceManager.GetString("CaptionQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コードに対する想いなど、ご自由に一言お願いします。.
        /// </summary>
        public static string CaptionQ4 {
            get {
                return ResourceManager.GetString("CaptionQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 創造する楽しみ・喜びのために。.
        /// </summary>
        public static string Choice1OfQ1 {
            get {
                return ResourceManager.GetString("Choice1OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書いた結果がすぐに動き出すのがおもしろい。.
        /// </summary>
        public static string Choice2OfQ1 {
            get {
                return ResourceManager.GetString("Choice2OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パズルを解くような楽しみ、問題を解く喜びがあるから。.
        /// </summary>
        public static string Choice3OfQ1 {
            get {
                return ResourceManager.GetString("Choice3OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人ととのつながりのために。.
        /// </summary>
        public static string Choice4OfQ1 {
            get {
                return ResourceManager.GetString("Choice4OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必要に迫られて。.
        /// </summary>
        public static string Choice5OfQ1 {
            get {
                return ResourceManager.GetString("Choice5OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稼ぐために。.
        /// </summary>
        public static string Choice6OfQ1 {
            get {
                return ResourceManager.GetString("Choice6OfQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下記の内容で回答を登録します。よろしいですか?.
        /// </summary>
        public static string ConfirmPrompt {
            get {
                return ResourceManager.GetString("ConfirmPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録頂いた内容は、インターネット上から自由に参照可能となります。またCode2012 イベント当日にも、回答内容の発表があります。.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code2012 アンケート.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        public static string UnitOfYears {
            get {
                return ResourceManager.GetString("UnitOfYears", resourceCulture);
            }
        }
    }
}
